### ISSUE TITLE
Consider allowing multiple valueNodeTypes

### ISSUE THREAD

**Issue by justinlittman** [dcmi/dctap#12]
For mapping Sinopia (BIBFRAME) Profiles to DCTAP (see https://github.com/LD4P/dctap), we need to treat valueNodeTypes as "zero or more" rather than the specified "zero or one".

The Sinopia Editor allows entering a literal in place of a URI. Thus, the valueNodeType would be `IRI|LITERAL`. The reason for allowing entering a literal in place of a URI is because some URIs for authorities may not yet have been created when a cataloger is creating a record.

**Comment by kcoyle** [comment]
@justinlittman Thanks for the comment. We discussed doing that (and could reconsider) but we saw a hitch. If your rule is:

IRI or LITERAL 

as the node, and you want to designate that the literal is an xsd:string in the valueDataType, and then you want designate that the xsd:string can have language tags @en, @fr, but the IRI is to be based on one or more IRIstems, like http://schema.org OR http://id.loc.gov --- Well, I think you can see that this doesn't work. In essence this would need to be split into two rows, one for each type, on order to be able to make specific constraints on the different types. I did envision a funky way to do that, which would go like this:

shapeID|shapeLabel|propertyID|propertyLabel|mandatory|repeatable|valueNodeType|valueDataType|valueConstraint|valueConstraintType|valueShape|note
----|----|---- | ---- |----|----| ---- | ---- |---- |---- |----|----
book|----|dct:subject | ---- |true|true| ---- | ---- |---- |---- |subject|----
subject||dct:subject|subject|false|true|LITERAL|xsd:string|@en,@fr|languageTag||
|||dct:subject|subject|false|true|IRI||http://id.loc.gov|||

Not exactly ideal. I'm not sure we can resolve this within the confines of the csv/tabular format. Plausibly a next step could be to move from those confines to something more forgiving (*cough* JSON), but using the same simple semantics. I would be thrilled to get ideas along this line, or solutions for the tabular format that we haven't seen.

**Comment by philbarker** [comment]
@kcoyle in your example, I am not sure about `subject` as a shape for use with property `dct:subject`, because it does not describe the value of a property. That is there is no value of `(book)--[dct:subject]-->` that has a property `dct:subject`. I think your TAP matches this data

```
<> dct:subject [ dct:subject "History"; dct:subject <http:://example.org/subject/history> ] .
```

(I guess I am saying that I think all our shapes are Node Shapes, we don't have Property Shapes; if we do we have the issue of how to say which is which.)

What I think would work is 

shapeID|propertyID|propertyLabel|mandatory|repeatable|valueNodeType|valueDataType|valueConstraint|valueConstraintType|valueShape|note
----|---- | ---- |----|----| ---- | ---- |---- |---- |----|----
book|dct:subject | ---- |true|true| ---- | ---- |---- |---- |  |----
 ||dct:subject|subject|false|true|LITERAL|xsd:string|`@en`,`@fr`|languageTag||
||dct:subject|subject|false|true|IRI||http://id.loc.gov|||

Which I would interpret as saying 
Line 1: there must be a subject
Line 2: subject may be a LITERAL
Line 3: subject may be as IRI

Still not ideal because there is no way of saying subject may NOT be a BNODE.

**Comment by kcoyle** [comment]
@philbarker This is a "hiccup" I've encountered before and admittedly skipped over it. I think I should open an issue, contingent on my being able to explain what I see as the problem. However, I think this is orthogonal to Justin's question, right?

**Comment by philbarker** [comment]
@kcoyle right. It's a detail in how we suggest a non-ideal approach to Justin's question. I agree that a full resolution might lie beyond what can be done in a TAP

**Comment by kcoyle** [comment]
In our discussion at the March 3 meeting we realized that the [vocabulary document](https://github.com/dcmi/dctap/blob/main/TAPvocabulary.md) is confusing and needs clarification.

The second column only indicates the cardinality of *columns* within the grouping units of profile, shape and statement constraint, to whit:
* A profile has zero or more shapes, and one or more statement constraints
* Each shape must have one shapeID, zero or one shape label, and one or more statement constraints
* Each statement constraint ... well, it's what it says there

This doesn't say anything about cardinality of *values* for the various elements. We went through those at the meeting and concluded that `valueDataType` and `valueShape` could have multiple "entries" in a single cell. There is interest in allowing multiple values in the two label columns, although we only see language labels as workable there. (There isn't a way to indicate a prefLabel vs an altLabel, for example.) We were hesitant about `valueNodeType` for the reasons given above, however there is some interest in defining a single string that would encompass IRI or BNODE. There are similar elements in both ShEx and SHACL.* We so far do not see a way to make IRI or LITERAL workable.

ACTION: @kcoyle will attempt an edit of the vocabulary document to reflect this.

\* Saying "OR" in data creation may not be as simple as testing for "OR" in data validation. In creation, you need some intelligence to make a choice, whereas in validation you are just testing some existing data. I worry about the ability of the TAP to fully define "OR" for either when the choice leads to paths with different criteria.

**Comment by kcoyle** [comment]
Here is the text I am suggesting to add to the [user document in the multiple values](https://github.com/dcmi/dctap/blob/main/TAPprimer.md#multiple-options-in-a-cell) section:

Not all columns can work well with multiple values. For example, one cannot have multiple values for the boolean elements of mandatory and repeatable. Likely uses of multiple values are: for labels (especially those using language tags to differentiate them); valueShape; valueConstraint; and valueDataType. Note that where multiple values are used one must be careful that this has not created ambiguity. For example, where there are multiple data types it may not be possible to also include a valueConstraint that would apply to only one of the multiple values.

**Comment by tombaker** [comment]
This issue is [addressed above](https://github.com/dcmi/dctap/issues/19#issuecomment-877747166) in #19.

I suggest we consolidate the thread by continuing discussion there and closing this issue.

**Comment by kcoyle** [comment]
This has been resolved to allow multiple types in the TAP vocabulary document.
