### ISSUE TITLE
Wikidata qualifiers in DCTAP?

### ISSUE THREAD

**Issue by tombaker** [dcmi/dctap#18]
@navino-evans

In Wikidata, if I correctly understand, a [qualifier](https://www.wikidata.org/wiki/Help:Qualifiers) is a statement -- a property-value pair -- about the value of a property given in a statement. Quite often, the value of a statement is qualified with multiple qualifiers. For example, the statement:

    Berlin (Q64) - has population (P1082) - "3,500,000"

has three parts, in Wikidata terminology:

    item - property - property value

The property value of this statement can be qualified by adding the following two property-pairs about the value "3,500,000":

    point in time (P585) - "2005"

    determination method (P459) - estimation process (Q791801)

or, in Wikidata terminology:

    qualifier - qualifier value

Could we accommodate these property-value pairs in a DCTAP spreadsheet in a way similar to how we handle shapes? In DCTAP, shapes are modeled like this, where `valueShape` references the `shapeID`:

    shapeID
        propertyID - [value constraints] - valueShape

    shapeID
        propertyID - [value constraints]
        propertyID - [value constraints]

Perhaps we could add four columns:  `valueQShape`, `qShapeID`, `qPropertyID`, `qValue`, such that the `valueQShape` references the `qShapeID`:

    shapeID
        propertyID - [value constraints] - valueQShape

    qShapeID
        qPropertyID - qValue
        qPropertyID - qValue

| shapeID   | propertyID   | valueConstraint   | valueQShape  | qShapeID | qPropertyID | qValue  |
| --------- | ------------ | ----------------- | ------------ | -------- | ----------- | ------- |
| :City     | P1082        | 3,500,000         | :CityQ       |          |             |         |
|           |              |                   |              | :CityQ   | P585        | "2005"  |
|           |              |                   |              |          | P459        | Q791801 |

**Comment by kcoyle** [comment]
Is there a reason that the `valueShape` wouldn't be sufficient for this?

| shapeID   | propertyID   | valueConstraint   | valueShape  | 
| --------- | ------------ | ----------------- | ------------ | 
| :City     | P1082        | 3,500,000         | :CityQ       | 
| :CityQ          |        P585      |    "2005"               | 
|           |   P459           |      Q791801             |

**Comment by tombaker** [comment]
@kcoyle I considered that. Shapes and "qualifier shapes" look to me like somewhat different things. I was perhaps wrong to call the qualifier shape `valueQShape` because it is not the case of a value resource, the description of which needs to conform to a shape. Rather, it is a shape for statements about an entire _statement_.

In other words, I may have been wrong in saying above that the statements are about the value "3,500,000" because it now looks to me like the qualifier-property/qualifier-value pairs are actually about the statement `has population (P1082) - "3,500,000"`. In other words, it is a form of reification (where statements are made about statements).

So maybe it's more like:

| shapeID   | propertyID   | valueConstraint   | statementQShape  | qShapeID | qPropertyID | qValue  |
| --------- | ------------ | ----------------- | ------------ | -------- | ----------- | ------- |
| :City     | P1082        | 3,500,000         | :CityQ       |          |             |         |
|           |              |                   |              | :CityQ   | P585        | "2005"  |
|           |              |                   |              |          | P459        | Q791801 |

Or even:

| shapeID   | propertyID   | valueConstraint   | statementQShape  | qShapeID | qPropertyID | qValue  |
| --------- | ------------ | ----------------- | ------------ | -------- | ----------- | ------- |
| :City     | P1082        | 3,500,000         | :CityQ       |  :CityQ  |  P585 |  "2005" |
|           |              |                   |              |          | P459        | Q791801 |

Or even:

| shapeID   | propertyID   | valueConstraint   | qPropertyID | qValue  |
| --------- | ------------ | ----------------- | ----------- | ------- |
| :City     | P1082        | 3,500,000         |  P585 |  "2005" |
|           |              |                   | P459        | Q791801 |

**Comment by philbarker** [comment]
> In other words, I may have been wrong in saying above that the statements are about the value "3,500,000" because it now looks to me like the qualifier-property/qualifier-value pairs are actually about the statement has population (P1082) - "3,500,000". In other words, it is a form of reification (where statements are made about statements).

Yes, that is my understanding. I think it is similar to property graphs and RDF-Star (at least the annotations in RDF-Star -- so perhaps we should think of solutions that work with RDF-star too).

Also  @tombaker's  example uses instance data as constraints. I think where you have "2005" and Q791801 the actual constraints would be a `valueDatatype` of xsd:date and some list of valid wikidata URIs.

Noting that the properties listed under qPropertyID are just properties, that happen to be used with a triple as their object, could we address this use case with a single new column of annotatingShape ("a shape be used to constrain annotations of statements made using this this property") and then define the shape as any other?

So: 

| shapeID | propertyID | propertyLabel | NodeType | valueDataType | valueConstraint | annotatingShape |
| ---------- | ---------------| ------------------- | --------------- |-------------------- | ---------------| ------------------ |
| City       | wdt:P1082  | population  | Literal | xsd:integer        |                   | PopAnnotation |
| PopAnnotation | wdt:P585 | point in time | Literal | xsd:date        |                  |                           |
|              | wdt:P459 | determination method |  IRI   |                         |  wd:Q791801 Q52679562 wd:Q??? ...   |      |    

Somehow the constraint on wdp:P459 in the PopAnnotation shape would have to express an appropriate sub set of what is shown at the bottom of https://www.wikidata.org/wiki/Property:P459, a pick list of URIs might be easiest.

So a valid Turtle-star example would be (I think)
```
wd:Q64 wdt:P1082 3500000 {| wdt:P585 "2005"^^xsd:date |} .
```

**Comment by philbarker** [comment]
@kcoyle the reason why `valueShape` wouldn't be sufficient is that you wouldn't know that it was the shape for the annotation not the value of the property (and at times you would need shapes for both).

**Comment by nishad** [comment]
Just for the discussion,

Can we model qualifiers and RDF-star approach together, if we are taking them as a different concept? In theory, qualifiers are metadata for the statements, and much similar to the RDF*.

**Comment by philbarker** [comment]
@nishad I think wikidata, RDF-star annotation syntax and maybe property graphs can be modeled in the same way. I'm not sure to model statements with embedded triples such as `<< wd:Q64 wdt:P1082 3500000 >> wdt:P585 "2005"^^xsd:date .` Perhaps it's as simple as an annotated/embedded/asserted flag for shapes used as annotations? There might be some tricky cases when there are multiple assertions and annotations, but maybe these require some other approach than RDF-star.

**Comment by kcoyle** [comment]
I like Phil's solution because it maintains the "shape-ness" of the annotation, isolating the value and its qualifiers. Does anyone have an example of a particularly complex wikidata schema that we can use to test out a knotty case? 

Also, are folks thinking of this as a local extension to TAP or something to be added to the TAP itself? (I prefer the former at the moment, but that's only because I don't know of other uses of this.)

**Comment by tombaker** [comment]
@kcoyle 
> are folks thinking of this as a local extension to TAP or something to be added to the TAP itself? 

For now, I think we should leave the issue open pending a better understanding of the implications, and we should invite further input. Eventually, I could see this going into an extension for Wikidata but, that said, it could be a pretty important extension given the size of the Wikidata community (ie, something more than "local").

**Comment by kcoyle** [comment]
I got curious about how Wikidata handles the qualifiers and spent way too much time reading through the [data format](https://www.mediawiki.org/wiki/Wikibase/DataModel) and [RDF dump format](https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format) documents on the WD site. From what I have understood (if my understanding is correct) we should be able to accommodate WD schemas with qualifiers without making any changes to TAP. Here's my take:

The way that Wikidata handles qualifiers is that it uses defined properties and gives them a special qualifier namespace represented with the prefix: "pq:", e.g. pq:P405, where P405 is the "taxon author" and pq:P405 would be a qualifier for the name of the taxon. Some qualifier properties are defined as being of owl:Class "qualifier" (https://www.wikidata.org/wiki/Property:P972) but others are not (https://www.wikidata.org/wiki/Property:P585). This may just be the "always in progress" aspect of Wikidata, or it could be that some properties can be both regular properties *and* qualifiers.

There are also "pqv" qualifiers which are less clear to me. The Wikidata RDF specification describes these two as:

>The qualifiers are represented by predicates with prefix pq: and the name of the property (e.g. pq:P2) and the object being the simple value of the qualifier.

>The full value (if required by the type) is represented by the predicate with prefix pqv: (e.g. pqv:P2) and the object being the full value node. 

Here is a snippet from https://www.wikidata.org/wiki/EntitySchema:E66, the schema for Mozart compositions. 

CATALOG

	p:P528 {
		ps:P528 xsd:string ;
		pq:P972 [
		        wd:Q162478 # Köchel catalogue
		        wd:Q22338962 # Köchel catalogue (1st edition)
		        wd:Q22340538 # Köchel catalogue (6th edition)
		        ];
	}+ ;

If I understand this snippet correctly, `p:P528` defines the entity, which would correspond to our shapeID. The `ps:P528` is a propertyID and of course xsd:string is the value datatype. `pq:P972` is the qualifier, and there are 3 items in its "picklist". I think this would look like this in TAP:

| shapeID | propertyID |valueDatatype| valueConstraint | valueConstraintType |
| ---- | ---- | ---- | ---- | ---- |
| p:P528 | ps:P528 | xsd:string | | | 
| pq:P972 | |  | wd:Q162478 wd:Q22338962 wd:Q22340538 | picklist |

Because the qualifiers "self-identify" with their namespace, and because WD code appears to treat them side-by-side with other properties, then it does not appear that they need a separate column in TAP. If this is not way off the mark then I think it would be useful to try to encode some full WD schemas in TAP and see if they can be translated back to WD schemas. I'll try to begin that, creating a directory under Examples for WD experiments.

**Comment by philbarker** [comment]
@kcoyle 
> If I understand this snippet correctly, p:P528 defines the entity,

The p: namespace is the property namespace, [p:P528](https://www.wikidata.org/wiki/Property:P528) is the catalogCode property, so I'm not convinced it is the shapeID.

But all I know about the wikidata model is that I don't understand the wikidata model.

**Comment by kcoyle** [comment]
@philbarker I find their terminology quite confusing, to be sure. They do say that "p:" is a property, and that "ps:" is the property statement. It is only "ps:" that takes a property value, such as "xsd:string", which makes it appear to be a property in the RDF sense. And the definition of "p:" is 

> Links an entity to a statement

Structurally, "p:" *seems* to act as a shapeID, and it also *seems* to usually have a blank node as a value, but that's my guess and the proof will be in the experimenting.

**Comment by navino-evans** [comment]
Hi all,
Sorry it's taken so long to join the discussion!

> Structurally, "p:" seems to act as a shapeID, and it also seems to usually have a blank node as a value, but that's my guess and the proof will be in the experimenting.

This is correct, it behaves in the same way as far as I can see.

The **p:** actually links to the "statement node", which has it's own unique ID on Wikidata. This in turn gives you access the qualifiers, references and other data related to the statement.

You can use the "simple value" **wdt:** relation instead. It will give you the value of the statement directly, but can't be used to access any further data about the statement.

For qualifiers, there is a similar "simple" vs "value node" distinction.
pq:  = simple value for a qualifier
pqv: = full value node, connected to more data (e.g.  time precision, units, globe for coordinates)

Here is a query which hopefully illustrates the actual stored values: https://w.wiki/3DNi

This page is the best portal of knowledge on this topic I think: https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format

The real gem is the [data model diagram](https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format#Data_model), but also there is a [complete list of all prefixes](https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format#Prefixes_used).

**Comment by kcoyle** [comment]
Thanks, @navino-evans - that gives me the impetus to work up some examples. I also have seen another Wikidata project that goes from data definition (which I think could be a TAP) to quick statements. When I figure that one out I will post my findings.

**Comment by kcoyle** [comment]
We should ping some wikidata folks to see how they like the examples, but nothing else needs to be done.
