### ISSUE TITLE
Scope of valueDataType

### ISSUE THREAD

**Issue by tombaker** [dcmi/dctap#24]
The current version of the [DCTAP Primer](https://github.com/dcmi/dctap/blob/main/TAPprimer.md) says:

> The value datatypes are literal datatypes, as defined in the XML schema datatypes specification (XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes). The list of datatypes there called "primitive" cover many of the most common metadata datatypes, including: string, boolean, decimal, float, double, duration, dateTime, time, date, gYearMonth, gYear, gMonthDay, gDay, gMonth, anyURI
> 
> These are usually preceded by a prefix (often "xsd:") which defines them as members of the XML schema vocabulary.
> 
> These datatypes are also valid for RDF nodes that are literals, as defined in RDF Concepts specification. (RDF Concepts - Datatypes)

However, DCTAP is designed for compatibility with RDF - a point that is implicit in parts of the primer but that should perhaps be said explicitly in the introduction. The [draft DCTAP vocabulary](https://github.com/dcmi/dctap/blob/main/TAPvocabulary.md), in my opinion, gets it right:

> This is for values with an RDF node type of "LITERAL". Where the instance metadata must be valid RDF literal value, as defined in (RDF Concepts - Datatypes). The majority of these datatypes are defined in the XML schema datatypes specification (XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes).

I propose that wording in Primer be changed to align with that of the draft vocabulary, for example:

> A value datatype is used with literal values (as defined in RDF Concepts) to indicate the nature of the literal, for example as a number, string, or date. A set of datatypes commonly used both in RDF and in XML data is defined in the XML Schema specification (XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes) and includes: string, boolean, decimal, float, double, duration, dateTime, time, date, gYearMonth, gYear, gMonthDay, gDay, gMonth, and anyURI. Datatypes are identified using IRIs, which may be abbreviated in a DCTAP table using the conventional prefix `xsd:` (eg, `xsd:time`).

Note: 
- My proposed wording encourages people to reference datatypes with IRIs or CURIEs. Applications may want to anticipate that people will use plain string values such as `boolean`, but we should IMO not actually encourage this in the Primer. The existing example in the Primer already reinforces this point.
- My proposed wording hints that datatypes are also defined elsewhere than just in XML Schema. I believe this is especially true for the sciences, though DCMI Metadata Terms also defines a dozen or so datatypes.

**Comment by kcoyle** [comment]
@tombaker Thanks. However, I prefer a wording that makes clear that TAP is not *only* for RDF data, but is compatible with RDF data. I believe that means that a valueDatatype could define an IRI if one's data is in JSON or XML or some other format. So how about:

> A value datatype is used to indicate the nature of the valid value for the property. A set of datatypes commonly used is defined in the XML Schema specification (XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes) and includes: string, boolean, decimal, float, double, duration, dateTime, time, date, gYearMonth, gYear, gMonthDay, gDay, gMonth, and anyURI. These datatypes are also valid for RDF nodes that are literals, as defined in the RDF Concepts specification. (RDF Concepts - Datatypes) Datatypes are identified using IRIs, which may be abbreviated in a DCTAP table using a prefix, such as `.xsd` for the XML schema set of datatypes.

**Comment by tombaker** [comment]
@kcoyle 
I agree with finding a way to make it clear that DCTAP is not just for RDF data. However...

> A value datatype is used to indicate the nature of the valid value for the property.

When put this way and presented along with the option `anyURI`, do we not lose the idea that `valueDataType` is specifically for literal values? In effect, this wording invites users to specify that the value is a URI by using `anyURI` instead of, or even in addition to, specifying `URI` under `valueNodeType`. I could have sworn that you have posted about this issue but do not see where.

**Comment by kcoyle** [comment]
It's #20 https://github.com/dcmi/dctap/issues/20. And while RDF may state that anyURI is a literal, the [XML document](https://www.w3.org/TR/xmlschema11-2/#anyURI) says:

> 3.3.17 anyURI

>[Definition:] anyURI represents an Internationalized Resource Identifier Reference (IRI). An anyURI value can be absolute or relative, and may have an optional fragment identifier (i.e., it may be an IRI Reference). This type should be used when the value fulfills the role of an IRI, as defined in [RFC 3987] or its successor(s) in the IETF Standards Track.

So by that definition, it *is* an IRI as per [IETF](https://www.ietf.org/rfc/rfc3987.txt). I don't know why RDF doesn't recognize that, but to me it seems logical that xsd:anyURI represents a URI/IRI.

**Comment by kcoyle** [comment]
@tombaker Ignoring the "anyURI" issue because we resolved that at the meeting, I do think that my wording is correct. It states that the value datatype, when used for RDF data, is only for literal datatypes. If used for other data formats (e.g. XML) that literal requirement isn't applied.

> These datatypes are also valid for RDF nodes that are literals, as defined in the RDF Concepts specification. (RDF Concepts - Datatypes) Datatypes are identified using IRIs

Perhaps the "also" in there is creating confusion? Maybe it should read:

> These are the datatypes that are valid for RDF nodes that are literals, as defined in the RDF Concepts specification. (RDF Concepts - Datatypes) Datatypes are identified using IRIs

**Comment by tombaker** [comment]
Should we perhaps close this?

**Comment by kcoyle** [comment]
I'm still interesting in figuring out what to do for folks who do not use RDF as their baseline format. Should I make that a separate issue?

**Comment by philbarker** [comment]
I'm interested in non-RDF usecases too, so +1 to it being a separate issue.

**Comment by kcoyle** [comment]
Unresolved questions have been opened in #42
