### ISSUE TITLE
Short forms for column headers

### ISSUE THREAD

**Issue by tombaker** [dcmi/dctap#34]
If all column headers are used, with commas, one CSV line is a minimum of 145 characters long:

```
shapeID,shapeLabel,propertyID,propertyLabel,mandatory,repeatable,valueNodeType,valueDataType,valueConstraint,valueConstraintType,valueShape,note
```

This is inconvenient both for editing and for display and is particularly inefficient for columns like 'mandatory' and 'repeatable', which take only one character as value.

I propose that each column have a shortform, eg:
- `sID` for shapeID
- `sLabel` for shapeLabel
- `pID` for propertyID
- `pLabel` for propertyLabel
- `mand` for mandatory
- `rep` for repeatable
- etc...

The [DCTAP Python script](https://github.com/dcmi/dctap-python) could easily expand these for purposes of display.

**Comment by tombaker** [comment]
I have implemented this (for now) as an undocumented feature. As an alias for each header, a short form is computed in the following way:
- first letter of the header, plus
- each uppercase letter

But case-insensitive, and squashing whitespace, dashes, and underscores, so the following variants should all work as aliases for valueConstraintType:
- vct
- VCT
- V    C    T
- V-c____t

As I say, undocumented... except here, of course.

**Comment by tombaker** [comment]
@philbarker 
I am removing the feature that calculated short header forms based on the first letter and each uppercase level because I think it has been superseded by the ability to define aliases in the configuration file. There was no ambiguity in the mappings FOR NOW, but I saw a risk of name clash if the default set of headers were to evolve, with potentially confusing results.

**Comment by philbarker** [comment]
OK, no problem.

Are the headings still treated as case/space insensitive?

**Comment by kcoyle** [comment]
This is incorporated into the config file of dctap-python.
