### ISSUE TITLE
Things "in data" vs "in DCTAP instances"

### ISSUE THREAD

**Issue by tombaker** [dcmi/dctap#35]
We talk about Statement Constraints, but this term is not actually used in the [Primer posted for review](https://www.dublincore.org/groups/application_profiles_ig/dctap_primer/). In order to clarify the distinction between "things in instance data" and "things in application profiles", I propose that we consistently use the following terminology:

| Instance data | Application Profile (about the instance data) |
| ------------- | ------------------ |
| __Entities__ (things described in instance data) | __Shapes__ (patterns for data describing given Entities |
| __Statements__ (property-value pair describing Entities | __Statement Constraints__ (patterns for Statements in the data) |
| __Properties__ (attributes of Entities) | __Property Constraints__ (patterns for Properties in the data) | 
| __Values__ (contents of the attributes of Entities) | __Value Constraints__ (patterns for Values in the data) |

**Comment by tombaker** [comment]
Or is it:

| In the World | In instance data | In an Application Profile |
| ----- | ------------ | ------------------ |
|  __Entities__  |  __Entity Descriptions__  |  __Shapes__  |
|  __Statements__ (in an abstract sense)  |  __ Statements__ (in a syntactic sense)  |  __Statement Constraints__  |
|  __Properties__ (in an abstract sense)  | __Properties__ (from controlled vocabularies)  |  __Property Constraints__  | 
|  __Values__ (in an abstract sense)  | __Values__ (in the data)  |  __Value Constraints__ |

Things "in the world":

- Entity: something described by Instance Data
- Statement: a claim that one makes about an entity
- Property: an attribute of an Entity, in an abstract sense
- Value (?)

Things "in the data":

- Entity Description: a set of property-value pairs used to describe an entity
- Statement: one of the property-value pairs that describe an Entity
  - Property: a named attribute from a controlled vocabulary
  - Value: a data value associated with a Property in the Instance Data

Things "in the profile":

- Shape: a pattern for data about a given Entity
  - Statement Constraint: a pattern for Statements in the data
    - Property Constraint: a pattern describing the use of Properties in the data
    - Value Constraint: a pattern describing the characteristics of Values in the data

Note: This model has a lot in common with the [DCMI Abstract Model](https://www.dublincore.org/specifications/dublin-core/abstract-model/), including a certain vagueness about whether a data value has some counterpart "in the world" along with a certain vagueness about the notion of a "description set" (DCAM terminology for the set of descriptions embodied in a "record") and its correspondence to the set of shapes that constitute an application profile.

**Comment by philbarker** [comment]
I think Object is better than "Value" in the real world -- you know the idea, and the arguments either way.

**Comment by tombaker** [comment]
@philbarker Agreed - a "value" is not something in the real world. Will edit above.

**Comment by kcoyle** [comment]
At our Dec 9 meeting @tombaker stated that we could use "description" as the term for the correspondent to "shape" but in the instance data. That doesn't work for me because description is both vague and used for various levels of metadata structures. I see above that Tom has used **entity description** and this is similar to what I have been thinking over the past few days: we can use description, but we have to qualify it with what it describes. We're all nervous about "entity" but I actually think this is the correct term in this case.

Another possibility would be to use "resource description" with "resources" being the things in the world. I hesitate on that because the RDF definition sounds like a single triple could be a resource description, and we are limiting our usage to one or more constraints on statements that together describe something (by use of a shapeID in TAP).

> "Any IRI or literal denotes something in the world (the "universe of discourse"). These things are called resources. Anything can be a resource, including physical things, documents, abstract concepts, numbers and strings; the term is synonymous with "entity" as it is used in the RDF Semantics specification [RDF11-MT]." [RDF Concepts 1.1](https://www.w3.org/TR/rdf11-concepts/)

Library RDA defines description: "A set of data recording and identifying an entity." (That's from an early version, since the current one is paywalled.) Resource is defined as: 
>"The term resource is used throughout RDA to refer to a work, expression, manifestation or item. If usage is restricted to a specific entity or entities this is indicated." 

which shows a mishmosh usage of resource and entity to the point that is isn't clear to me. But they do seem to use "description" as relating to FRBR "entities" - aka WEMI - which is broader than our "shape" definition. 

Just to make things less clear, [BIBFRAME](https://www.loc.gov/bibframe/docs/bibframe2-model.html) uses "resource" for the whole thing being cataloged, and "description" for describing that whole thing:

>"When a resource is cataloged  -- a book, for example -- the resulting description includes information elements such as the author, what the book is about, various published forms, and  information about copies of the book." 

However I suspect that this is not the final word but so far I haven't located a document that I think is more authoritative. I did find that [Sinopia](https://docs.google.com/presentation/d/1n7i1IJ8dk0MGLzGnmIhkodKg_NLUgp98GtRFyhsRZBg/edit#slide=id.p1) also refers to entire records as "descriptions". 

I also looked at XML schema and JSON but didn't gain much from those documents. I will note that it appears that XML uses "element" in a way that nears the concept of "statement constraint". But hopefully someone else has a clearer idea.

**Comment by kcoyle** [comment]
Here are some more terms as they are used in metadata formats:

**XML** has elements, attributes, and child elements. Anything with bracketed keywords is an element. Elements within element bracket sets are child elements. In addition, an element can have attributes, which are key/value pairs. See: https://www.w3.org/TR/2008/REC-xml-20081126/

**JSON** 
>JSON is built on two structures:
>    A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
>    An ordered list of values. In most languages, this is realized as an array, vector, list, or sequence.
from: http://www.json.org/json-en.html

I'll try making this and the above into a table.

**Comment by philbarker** [comment]
I have had a go at revisiting this. In summary:

For **real world things**: use entity, characteristics, relationship and entity class or type of entity.

For **metadata**: use instance (data), statements, subject, predicate, object, value.

For **schema**: use vocabulary, term, property, (metadata) class, ontology, concept scheme.

For **application profiles** (especially TAPs): use rule, statement constraint, element, shape, column, row, entry.

I've put [some text into hackmd](https://hackmd.io/7RT1MstvS7yumgVwbtFm2A) which might be useful as an appendix in the primer, if you like these suggestions.

**Comment by kcoyle** [comment]
@philbarker I LOVE this! Especially the text in hackmd. To me this is clear without being jargon-y. We can perhaps go over it at a future meeting, but I agree that this would make a good appendix. The primer could say: for more clarification on terminology used here, see appendix X.

I does seem that using this would be a change from terms we have been using up until now. I'm not sure where/if all of the changes would need to take place. Do you think these terms could be used in the [vocabulary document](https://github.com/dcmi/dctap/blob/main/TAPvocabulary.md)? Or would that continue to use more formal terminology?

**Comment by philbarker** [comment]
@kcoyle :smile: thank you! That's what I was hoping for.

Yes, I think we will have to make some changes. The suggestions/comments I made on the primer last week were mostly prompted by this thinking, but I hadn't written anything down so it wasn't all as thought through as it could have been. Hopefully if we can agree guidelines like these the changes will be more editorial and require less discussion. I think the vocabulary doc should follow the same principles, and I think mostly it already does, but will should be more formal (as it already is).

**Comment by tombaker** [comment]
@philbarker Finally got to give this a careful read and agree with @kcoyle - it is brilliant! 🥇  A few quibbles but nothing, I suspect, that we cannot resolve. In fact, I think it could go into an appendix, but it could also stand on its own as a one-page style guide for writing about these topics. Also, if we can agree on terminology, we could perhaps put this into the  [DCMI glossary](https://www.dublincore.org/resources/glossary/) that has not been updated in awhile.

**Comment by kcoyle** [comment]
I mentioned the Singapore Framework in the recent meeting:
![singaporeFramework](https://user-images.githubusercontent.com/1564129/152821819-72ce3b85-73b0-4a0b-b5b0-4062f68474ca.png)
This includes functions we haven't included in TAP so I see TAP as encompassing the position of the description set profile, and perhaps also the domain model (the shapes). 

Looking at the framework above, the AP includes vocabulary, constraints, format, and model, plus human-oriented instructions.  That's broader than TAP. But the context is that the AP exists within a particular environment that includes the community domain model. We've said that an AP can be just "a selection of terms from one or more vocabularies".  That seems to me to be too basic because it sounds like an AP can be an entirely new metadata expression, not based on any existing model, rather than being the documentation of a practice within a particular metadata environment. I think we need to get the concept of "metadata environment" into our picture of what a TAP is.

**Comment by kcoyle** [comment]
This may need its own issue, but I want to put TAP into a context like the one in the Singapore Framework. I think it can be done with a sentence or two in the primer, such as:

"Within a community that creates and shares metadata there is often the need to work with variations of the general metadata framework that has been agreed upon. These variations can address specific application functions, such as different outputs, or they can reflect the data options of different metadata contributors."

Then where we have the section on listing properties, we could say that properties could come from an existing schema or practice, and that they AP can be a subset of an existing schema, or it could include necessary properties from other vocabularies. 

I don't think I've got that all worded right, but hopefully you can see how this incorporates the context that the Singapore Framework provides. And it differentiates between creating a new metadata schema (using existing vocabularies) and creating an application profile. It's the difference between these two that has been niggling at me.

**Comment by tombaker** [comment]
[Where we are now](https://hackmd.io/7RT1MstvS7yumgVwbtFm2A?view) compared to where we were [last June](https://github.com/dcmi/dctap/issues/35#issue-917299233).Note the question marks here and there.

| World       | Metadata instance              | Application Profile   | Vocabulary |
|-------------|--------------------------------|-----------------------|------------|
| Entity      | Subject, a Node               | Shape                 | Class? [1] |
| Entity      | Statement                      | Statement Constraint  |            |
| Characteristics, Relationships [3]         | Predicate                      | Predicate Constraint? | Property   |
| Entity? [5] | Object, aka Value [4], a Node | Value Constraint?     |            |

1. A class (as a type of term) may be used to identify explicitly the type of an entity.
2. Set of constraints on a value for a single characteristic of a single entity.
3. Characteristics of entities and relationships among entities.
4. The object of a statement is called the value of the property in a metadata instance.
5. Because the object of a statement can be an identifier for a related entity.

In other words:
- An entity is a thing in the world.
- Metadata is composed of statements about entities.
  - Entities are the subjects, and sometimes the objects, of statements.
- Vocabularies define the properties and classes used to make statements about entities.
  - Properties are used in metadata as predicates, which identify a characteristic of the entity that is the subject of the statement, or identify a relationship between a subject entity and an object entity.
  - Classes are sometimes used in metadata to identify explicitly a type of thing to which a subject entity belongs.
- A shape is a set of statement constraints that applies to a single entity or concept.
  - A statement constraint is a set of constraints about a single statement?
  - A predicate constraint is a constraint on a predicate (eg, the identifier of a property).
  - A value constraint is a constraint on the object of a statement.

**Comment by tombaker** [comment]
@philbarker @kcoyle @nishad @johnhuck 
I see some weaknesses in the above:
- The style guide says that an application profile comprises a set of constraints on metadata statements and that "A set of statement constraints that applies to a single entity or concept is called a shape." This seems to imply that a single "statement constraint" applies to a single statement. On the other hand, I think we'd probably agree that the various constraints on predicates and values are, generically, "statement constraints".
- The TAP model explicitly names types of value constraint (`valueNodeType`, `valueDataType`...), so I guess we'd call them, as a whole, "value constraints". Logically, then, I guess we'd talk about "predicate constraints", though we currently only have one, `propertyID`, which is enough for our purposes.

To be honest, I think Phil's style guide is about as far as we should go in the direction of formalization. In addition, I would like to have a nice simple table to show - one that is much simpler than the table above.

**Comment by tombaker** [comment]
Here is the simpler view I'm itching to present.

| Reality | Metadata Instance                 | Application Profile     | Vocabulary |
|---------|-----------------------------------|-------------------------|------------|
| Entity  |                                   |                         | Class?     |
|         | Set of Statements about an Entity | Shape                   |            |
|         | Statement                         | Statement Template      |            |
|         | - Predicate                       | - Property Constraints  | Property   |
|         | - Value                           | - Value Constraints     |            |

The table could say "Set of Constraints on a Statement", but I do still wish we could say "Statement Template" for the reasons I outlined [in March](https://github.com/dcmi/dctap/issues/66#issuecomment-1077683322), in part because this could put us into alignment both with Bibframe and with DCMI's own published [DC-DSP](http://dublincore.org/documents/dc-dsp). It seemed like we were getting closer to a deal when @kcoyle suggested that ["template" could work](https://github.com/dcmi/dctap/issues/66#issuecomment-1077744378) as long as we could make clear that we do not mean template in the sense "user interface form to be filled in" but as a set of constraints on a statement.

I have penciled in "property constraints" because "property and value constraints" sounds better, even if "predicate constraints" would more faithfully reflect the distinction we make in the style guide between predicates and properties.

I added "Class?" with a question mark because there is not actually any requirement that the type of entity be explicitly asserted with a class.

**Comment by philbarker** [comment]
See "style guide" https://hackmd.io/7RT1MstvS7yumgVwbtFm2A?view
