### ISSUE TITLE
min/max string length

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#56]
We have two examples now in which folks want to define the maximum length of a string ("text field"), and one in which there is a minimum length defined. XML schema has:

* [minLength](https://www.w3.org/TR/xmlschema11-2/#rf-minLength)
* [maxLength](https://www.w3.org/TR/xmlschema11-2/#rf-maxLength)

These are not data types in XSD, but ["constraining facets"](https://www.w3.org/TR/xmlschema11-2/#rf-facets), and in TAP they would logically be value constraints.

**Comment by philbarker** [comment]
I added the following to https://hackmd.io/V3LGdBdxTrOid57M2wJUlw :

## Minimum/maximum string lengths

([#56](https://github.com/dcmi/dctap/issues/56))

Sometimes it is desirable to limit the length of a string, for example to avoid overly long or too short descriptions. 

One approach for doing this is to have a `valueConstraintType` such as `minLength` and `maxLength` (these terms follow the vocabulary found in the SHACL and XML Schema standards). The entry for the `valueConstraint` is then interpreted as the appropriate limit on the character length. For example, to limit descriptions to 512 characters:

| propertyID | propertyLabel | valueConstraint | valueConstraintType  |
|-|-|-|-|
| dc:description | Description | 512 | maxLength |
