### ISSUE TITLE
min/max value 

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#57]
Probably used only with numerical values, there is a need to give the minimum and maximum numerical value that a property value can have. Easy examples are:

* for K-12 school children, ages 4-18
* for date of birth, 1950-2015
* etc

XSD schema has these as:
* [maxInclusive](https://www.w3.org/TR/xmlschema11-2/#rf-maxInclusive)
* [maxExclusive](https://www.w3.org/TR/xmlschema11-2/#rf-maxExclusive)
* [minInclusive](https://www.w3.org/TR/xmlschema11-2/#rf-minInclusive)
* [minExclusive](https://www.w3.org/TR/xmlschema11-2/#rf-minExclusive)

While these are functionally correct, the concept of inclusivity may not be common. We could decide that one of these, perhaps "inclusive" set, is the default if one uses a simple min/max. Ideally we would find an existing standard that could be used. It does appear that the SPARQL [min/max functions](https://www.w3.org/TR/sparql11-query/#defn_aggMin) have the inclusive meaning, but I'm not sure if they can be used as intended in TAP, SPARQL being a very specific context.

**Comment by philbarker** [comment]
I have added the following to https://hackmd.io/V3LGdBdxTrOid57M2wJUlw

One approach to providing minimum and maximum values is to extend the value space for the `valueConstraintType` to include terms such as "min", "max", "minInclusive", "maxInclusive". The entry in the `valueConstraint` cell is then interpreted accordingly. For example if the `valueConstraintType` is "min" and the `valueConstraint` is "6" then the value must be over 6; or, if the `valueConstraintType` is "minInclusive" and the `valueConstraint` is "6" then the value must be 6 or over. 

| propertyID | propertyLabel | valueConstraint | valueConstraintType  |
|-|-|-|-|
| ex:age | Age | 6 | min | 
| ex:age | Age | 18 | max | 


This approach of using the valueConstraintType has the advantage over an alternative of adding columns for each type of constraint (min, max, etc) that it does not lead to wide tables with many, sparsely populated columns, requiring much horizontal scrolling.

It is sometimes necessary to specify both the upper and lower bounds on numeric values. This can be achieved without repetition of the row, by using terms such as "range" and "rangeInclusive" as the `valueConstraintType` so long as some convention is agreed for a separator to be used between the upper and lower bound in the `valueConstraint` column. For example:

| propertyID | propertyLabel | valueConstraint | valueConstraintType  |
|-|-|-|-|
| ex:age | Age | 6-18 | range |

**Comment by kcoyle** [comment]
Added to cookbook.
