### ISSUE TITLE
valueDataTypes for Shapes

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#61]
I believe that I have erroneously at times included a valueDataType on a row that also has a valueShape. Should we 

* declare that a row with a valueShape has no valueDataType?
* allow valueNodeType on rows with a valueShape? If so, only IRI or BNODE?
* create a valueDatatype of "shape" for those rows?

**Comment by philbarker** [comment]
I wonder if @tombaker's dctap-python validates this type of error? 

Bearing in mind that data types are qualifiers for Literals (at least in RDF) and that our idea of a shape doesn't really apply to Literals, I think that the valueNodeType should drive the rules:
if valueNodeType == IRI or BNode, you can have valueShape but not valueDataType
if valueNodeType == Literal, you can have valueDataType but not valueShape

(or to answer your questions: yes, yes, no)

**Comment by kcoyle** [comment]
Thanks, @philbarker These are very clear rules and I think they cover the question. I can add this to the Primer in the section on Shapes.

**Comment by kcoyle** [comment]
Here's some wording:
When a statement constraint has a `valueShape`, `valueDataType` is left blank.
For profiles defining RDF data, the `valueNodeType` of statement constraint with a `valueShape` can be `IRI` or `BNODE`. A `valueNodeType` of `literal` cannot be used with a valueShape.

**Comment by philbarker** [comment]
How about (for symmetry and adding rationales):
A statement constraint will not normally have both a `valueShape` and a `valueDataType`.
For profiles defining RDF data, if the statement constraint has a `valueNodeType` that is  `IRI` or `BNODE` it should not have a `valueDataType` as a datatype describes literals; if it has a `valueNodeType` that is `LITERAL`  it should not have a `valueShape` as shapes describe non-literal data.

**Comment by kcoyle** [comment]
This is now in the primer.
