### ISSUE TITLE
Content vs structure

### ISSUE THREAD

**Issue by HughP** [dcmi/dctap#79]
Greetings,

@kcoyle It was great to hear your presentation at the DC-2022 panel. I'm curious how DCTAP has approached the question of content standards. As I understand the situation from your presentation, the tabular application profile has all the advantages of presenting a "light weight" metadata schema to organizations just starting to describe their collections. It works with the target audience in that it accommodates the spreadsheet or "tabular view". It is also flexible, in that it allows young organizations to define their application profiles by selecting the most meaningful (to them and their audiences) metadata elements from wherever they are in the metadata universe (regardless of namespace or schema). My question is **_how does it dctap move beyond structure (syntax) and into supporting content in the fields_** — for example, some organizations follow DACS, while other metadata schemas are both a structure and a content standard. In the sense that DCTAP assists people and organizations starting out, how does it seek to support standardized content description within an organization's implementation of DCTAP?

**Comment by kcoyle** [comment]
@HughP I think you are asking about validation. If not, let me know. DCTAP describes rules that MAY be used for validation, but it does not itself validate. Validation methods, like ShEx or SHACL, can take DCTAP as input, and we have some experiments on-going that follow that flow. 

The other aspect of that is input control, aka data entry rules. We haven't yet created an input form from a DCTAP but think it could be done.

If an organization wishes to follow a set of cataloging rules, like DACS, it has to write those rules into the DCTAP. However, without a defined machine-readable vocabulary the DCTAP is just more documentation that can't be immediately actionable, and that requires a human to analyze the results.

**Comment by HughP** [comment]
@kcoyle You are right, in fields like dates or URI this would be data validation. But I wasn't primarily thinking about this. I was thinking about description fields and free-text type fields which is why I referred to DACS. Os I was seeing that each field does need a reference to a content standard's discussion of the relevant field.

**Comment by kcoyle** [comment]
You can include the field references in the notes column of DCTAP, or by adding a field specifically for those. We've also had examples where people want to include examples for fields, and for those you would want to add a special column. DCTAP is extensible by simply adding more columns - like DC Terms we found what we considered to be a "sweet spot" and stopped there because the potential universe of columns was overly large and we had no metrics for deciding which to include - we erred on the "minimalist" side.

**Comment by kcoyle** [comment]
@HughP Can we close this one? Thanks.
