### ISSUE TITLE
Open/closed profile

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#8]
*See [dcap issue 33](https://github.com/dcmi/dcap/issues/33)*

- Open would mean that other properties or shapes are allowed
- Closed would mean only what is in the template is allowed

Should this be at the shape level? or the profile level? or both?

- At the shape level this controls the what property IDs are valid.
- At the profile level this controls what shapes are valid.
(This probably can't apply to the property constraint level, as that level applies to the property/value pair and would make value definitions "open")

**Comment by tombaker** [comment]
+1 for shape level

At the shape level, however, I see this as being not about closing a set of allowable property IDs, but about closing the set of properties-with-value-constraints. It is not uncommon to need to use the same property more than one way within the context of a shape - that is, one property used with two different sets of value constraints. For example:

| shapeID | propertyID | valueShape |
| -------- | -----------|------------|
| :BugReport | ex:reproducedBy | :Programmer |
|  | ex:reproducedBy | :Tester |

I'm not sure I understand what it would mean to say that "closed" applies at the profile level. Let's say a profile defines two shapes, Book and Person. In declaring that profile to be closed with regard to shapes, would one be saying that the profile would not match a dataset that contained things that matched a hypothetical Article shape - without actually declaring that Article shape? An example would help me understand.

**Comment by kcoyle** [comment]
@tombaker -  clarifying from your statement that a closed shape includes the full description of the statement constraints, thus the statement constraints are always closed in a closed shape. Is that what you mean? 

I don't know, though, how one validates a statement constraint in an open shape. I can see it allowing additional statement constraints, and presumably the ones that are mandatory must meet the full definition of the statement constraint, including value types. However, optional statement constraints, if the propertyID matches, are more difficult. I can imagine the same propertyID but not matching the defined value constraints - would that be an error? Or an additional statement constraint? If the latter, then it becomes difficult to validate those optional statement constraints, because the status of "open" means that the statement constraint definition on optional properties is not limited to the constraints defined in the profile. I think we need to work through this algorithmically within various scenarios, like creation, validation, ingest. I'll try to work up some examples.

> In declaring that profile to be closed with regard to shapes, would one be saying that the profile would not match a dataset that contained things that matched a hypothetical Article shape 

I see two scenarios for a closed profile: 1) data creation, where the data creation interface would include *only* the shapes and statement constraints in the profile and 2) data selection, where one is selecting specific shapes from a larger pool of data using a profile. (There may be others, these two immediately come to mind.) 

I'm having a harder time coming up with practical scenarios for open profiles, so would love for folks to articulate some.

**Comment by tombaker** [comment]
@kcoyle
> statement constraints are always closed in a closed shape

That is not what I meant, rather: Statement constraints are **always** closed in the sense that they "close" the use of a property to describe a given node. For example, if a value constraint says that `dc:creator` must be used with a literal value, then an outgoing arc from that node in the data using `dc:creator` with an IRI would not be valid. 

This is why cardinality constrains the use of an entire statement constraint - property PLUS value constraints - not just the use of its property.

To put it another way: If cardinality referred only to the use of the property, then there would be no way to express the idea that whenever `dc:creator` is used, it must be used with a literal value (which is the very purpose of application profiles as we have been discussing them).

Note that in the [example above](https://github.com/dcmi/dctap/issues/8#issuecomment-753331677), repeating the property`ex:reproducedBy` means that it can be used with values that match either of two value constraints. Note also that "closing" the use of a property with respect to value constraints, in the context of a Statement Constraint, does not mean that the Statement Constraint as a whole must match any arcs in the data if its cardinality has been defined as "not mandatory".

**Comment by tombaker** [comment]
@kcoyle 
> However, optional statement constraints, if the propertyID matches, are more difficult. I can imagine the same propertyID but not matching the defined value constraints - would that be an error? 

I think you are asking the following: If `dc:creator` were associated in a statement constraint with the value constraint "must be literal", and an arc with `dc:creator` were found in the data with an IRI value, would it be an error?

Yes, I would expect this to be an error. While the Statement Constraint need not have a matching arc in the data (because it is not mandatory), that non-mandatory Statement Constraint is closing the use of the property mentioned, so its use with an IRI as value would not be allowed.

**Comment by tombaker** [comment]
To put it another way: A shape groups statement constraints about the outgoing arcs of a node in the data.

Closing a shape means: "All outgoing arcs must match Statement Constraints in the Shape." That is, all outgoing arcs must use properties mentioned in the Statement Constraints with values that match the corresponding value constraints.

The default open shape means: "All outgoing arcs that use properties mentioned in the Statement Constraints must also match their value constraints. But any additional outgoing arcs - arcs that do NOT use properties mentioned in the Statement Constraints for a Shape - are allowed (ignored)."

**Comment by kcoyle** [comment]
I've started a document to try to work out enough examples to clarify the meaning of open and closed. I think that examples will help.

https://docs.google.com/document/d/1BGgJ9wjh1_pdIx6ecF8B4uew9wJpsbCi7qFOWy-5-IY/edit#heading=h.ikg3cwej7d3p

**Comment by kcoyle** [comment]
It occurs to me that since the concept of "open" in semantic web is probably more open than we'd find useful it might be best to use "strict/loose" (or something equivalent) rather than "open/closed".

**Comment by kcoyle** [comment]
Here's an attempt at flow-charting "closed" - will soon upload "open" (hopefully).
![closed 1](https://user-images.githubusercontent.com/1564129/103500324-d0cc9600-4dff-11eb-85de-2a824552a525.jpeg)

**Comment by philbarker** [comment]
Tom [wrote](https://github.com/dcmi/dctap/issues/8#issuecomment-753462297):

> The default open shape means: "All outgoing arcs that use properties mentioned in the Statement Constraints must also match their value constraints. But any additional outgoing arcs - arcs that do NOT use properties mentioned in the Statement Constraints for a Shape - are allowed (ignored)."

The first sentence seems too strict to me. If an open profile specifies that dc:creator is constrained to Literal values, then I would say that any instance that had a statement with a Literal value for dc:creator would be valid. If it also had a statement with dc:creator and a URI value, then fine.

In other words I interpret the constraints in an open profile as saying "there must be statements that satisfy these constraints, but it doesn't matter what other data there is".

**Comment by tombaker** [comment]
@philbarker "All outgoing arcs that use properties mentioned in the Statement Constraints must also match their value constraints" is at any rate consistent with the [default interpretation of a shape in ShEx](https://shex.io/shex-primer/#extra-properties). In ShEx, an individual property can be "opened" - made usable with other, unspecified constraints - by using a keyword, `EXTRA`.

I'm currently thinking that details like this should perhaps be considered out of scope for DCTAP. We could, for example, explain and discuss scenarios in which one might want to consider entire shapes, or their mentioned properties, as open or closed, but leave such details to implementers. For csv2shex, for example, I could clarify how a CSV is translated into ShEx, and I could support an additional column (outside of the DCTAP model) along the lines of `propertyExtra`, with a default of False.

**Comment by kcoyle** [comment]
Deferring this for now, with hope that experience with implementations will give guidance on the best solution.
