### ISSUE TITLE
"Implicit" shapes

### ISSUE THREAD

**Issue by tombaker** [dcmi/dctap#85]
@kcoyle 
In our discussion yesterday of the [DCTAP vocabulary](https://github.com/dcmi/dctap/blob/main/TAPvocabulary.md), I thought I heard someone suggest that, in effect, the uppermost ["component"](https://github.com/dcmi/dctap/commit/85fbdc0e5f7022e95b1ee2de3a6b30b4f22c330d) could be either  a Shape or a Statement Constraint. I propose another way to see this.

In dctap-python I assumed that, for the sake of consistency in processing, the module should _always_ output a Shape, regardless of whether that shape were explicitly declared. For example, when interpreting the  [most minimal DCTAP](https://dctap-python.readthedocs.io/en/latest/model/minimum_profile/index.html) profile -- a simple list of properties -- the module should, in effect, _infer_ the existence of a default shape. In dctap-python, the default name for that default shape is (drum roll...), `default` :-), but this can be [configured](https://dctap-python.readthedocs.io/en/latest/elements/shapeID/index.html#elem-shapeid) to be anything else.

In other words, given a simple list of properties, the dctap module returns (here: in user-friendly syntax):

    DCTAP instance
        Shape
            shapeID                  default
            Statement Template
                propertyID           http://purl.org/dc/terms/title
            Statement Template
                propertyID           http://purl.org/dc/terms/publisher
            Statement Template
                propertyID           https://schema.org/creator
            Statement Template
                propertyID           http://purl.org/dc/terms/date

I propose that we say that for DCTAP profiles about data for a single resource, a shape need not be declared, but that in accordance with the DCTAP model, the existence of a shape, as a grouping construct for the statement constaints, will nonetheless always be inferred.

We could add that this default shape can, in principle, be ignored by consuming applications downstream while pointing out that the existence of a shape - because it can always be inferred - simplifies processing.

**Comment by philbarker** [comment]
I think that makes sense, though hopefully most of the users who just want a simple property list will never know about it.

**Comment by kcoyle** [comment]
I agree with Phil but I am also having a devil of a time showing this as a diagram. I'm actually thinking that it will require at least two different diagrams, one showing a dctap with one or more actual shapes, and one showing a dctap without a defined shape. Once you put the shape in the diagram it's hard to show that it's "imaginary" in some cases.

**Comment by tombaker** [comment]
@kcoyle maybe use a dotted line for the box?

**Comment by kcoyle** [comment]
@tombaker I had that idea as well. Haven't tried it yet.

**Comment by kcoyle** [comment]
Add to cookbook - if no shape defined, implies a shape.

**Comment by kcoyle** [comment]
This is now in the primer: "In the most simple DCTAP, one that contains only one set of properties and constraints, that profile can be understood as representing a single, default shape. In this sense all DCTAPs can be said to be made up of at least one shape."
