### ISSUE TITLE
Pesan apa pun yang dihasilkan oleh program. Saya tidak tahu bahwa itu "opsional" - mungkin siapa pun yang menjalankan program akan ingin tahu apakah ada pesan atau kesalahan. Dengan meja besar, meminta mereka pergi ke layar mungkin tidak cukup. Ini adalah sesuatu yang perlu kita diskusikan sebagai bagian dari output, jadi saya akan menambahkannya ke agenda.

### ISSUE THREAD

**Issue by Mida-11** [dcmi/dctap#89]
Whatever messages are produced by the program. I don't know that it is "optional" - presumably anyone running the program will want to know if there are messages or errors. With a large table, having those just go to the screen may not be sufficient. This is something we need to discuss as part of output, so I will add it to the agenda.

_Originally posted by @kcoyle in https://github.com/dcmi/dctap/issues/32#issuecomment-856789974_

**Comment by kcoyle** [comment]
(re-wrapping for better readability)
@Mida-11 Mida-11 mentioned this issue Jan 19, 2023
Any messages generated by the program. I didn't know that it was "optional" - maybe whoever is running the program will want to know if there is a message or error. With a large table, having them go to the screen may not be enough. This is something we need to discuss as part of the output, so I'll add it to the agenda.

**Comment by kcoyle** [comment]
No further discussion, not sure what the question was. Could be spam?
